"""empty message

Revision ID: 137933c07094
Revises: 4d761ffb422a
Create Date: 2019-11-27 16:33:22.802663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "137933c07094"
down_revision = "4d761ffb422a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
