"""empty message

Revision ID: 4d761ffb422a
Revises: 922ebfe6ce0f
Create Date: 2019-11-27 16:05:01.207221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4d761ffb422a"
down_revision = "922ebfe6ce0f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
