"""empty message

Revision ID: 53855ae22e60
Revises: 137933c07094
Create Date: 2019-11-28 10:36:06.672172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "53855ae22e60"
down_revision = "137933c07094"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
