"""empty message

Revision ID: 922ebfe6ce0f
Revises: 33b264bd5a48
Create Date: 2019-11-26 23:34:13.260816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "922ebfe6ce0f"
down_revision = "33b264bd5a48"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_mobile_phone_key", "users", type_="unique")
    op.drop_column("users", "mobile_phone")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "mobile_phone", sa.VARCHAR(length=64), autoincrement=False, nullable=True
        ),
    )
    op.create_unique_constraint("users_mobile_phone_key", "users", ["mobile_phone"])
    # ### end Alembic commands ###
